### ISSUE TITLE
Создание страниц для историй

### ISSUE THREAD

**Issue by TorinAsakura** [taPublic/bogorodsky#11]
Сабж. Необходимо для каждой истории сделать страницу которая имеет:
- заголовок
- краткое описание
- фото
Я в них выгружу все записи по релевантным тегам и красиво стилизую.
А пока будет висеть прототип.

**Comment by OlgaGost** [comment]
А нельзя сделать некий шаблон, в котором будет меняться описание в зависимости от истории?

**Comment by OlgaGost** [comment]
Просто добавив, например, рубрику истории?

**Comment by TorinAsakura** [comment]
Я сделаю блок генерируемым, и автоматизирую процесс, для этого и нужны страницы, для тестирования.
P.S: Истории это просто набор записей по собранных по признаку. Как только историй будет больше чем, скажем, 3, блок будет трансформирован в карусель

**Comment by OlgaGost** [comment]
Коронавирус: Во время пандемии коронавируса очень важно выработать правильную тактику. Все о том, как сдерживают распространение вируса в Богородском городском округе.

**Comment by TorinAsakura** [comment]
> Коронавирус: Во время пандемии коронавируса очень важно выработать правильную тактику. Все о том, как сдерживают распространение вируса в Богородском городском округе.

Зачем ты пишешь это сюда? Создавай страницу
