### ISSUE TITLE
Видео

### ISSUE THREAD

**Issue by OlgaGost** [taPublic/bogorodsky#3]
1. Необходимо завести блок Видео, отображающийся в меню.
2. Контент будет выглядеть так: Заголовок, видео по ссылке с ютуба, подпись.

**Comment by OlgaGost** [comment]
Остановим вирус под Москвой!
https://youtu.be/r-0w3J5elcM 
Звезды рассказали о том, как вести себя в период эпидемии коронавируса.

**Comment by OlgaGost** [comment]
Считаем дни до Победы
https://www.youtube.com/watch?v=zagCjSsDw6E
Богородцы принимают активное участие в проект "75 дней до Победы" . Начиная с февраля они записывают стихи,  песни, рассказы о Великой Отечественной войне.

**Comment by OlgaGost** [comment]
Считаем дни до Победы
https://www.youtube.com/watch?v=9f99Uf6OXZU
Богородцы принимают активное участие в проект "75 дней до Победы" . Начиная с февраля они записывают стихи, песни, рассказы о Великой Отечественной войне.

**Comment by TorinAsakura** [comment]
@OlgaGost два видео с одним и тем же контентом не прокатит, или или

**Comment by OlgaGost** [comment]
Считаем дни до Победы
https://www.youtube.com/watch?v=hc1aGD_WH38&t=9s
Богородцы принимают активное участие в проект "75 дней до Победы" . Начиная с февраля они записывают стихи, песни, рассказы о Великой Отечественной войне.

**Comment by TorinAsakura** [comment]
@OlgaGost если их больше двух это уже в истории может пойти

**Comment by OlgaGost** [comment]
Про родного героя
https://www.youtube.com/watch?v=hc1aGD_WH38&t=9s
Акция #прогероя призвана сохранить память о тех, кто сражался за родину - фронтовиках, партизанах, тружениках тыла, узниках концлагерей, блокадниках, детях войны. У многих жителей Богородского округа есть семейные архивы, хранящие память о военном времени.

**Comment by OlgaGost** [comment]
Делегация Богородского городского округа в Белоруссии
https://www.youtube.com/watch?v=wiTfiyOT02Y&feature=share&fbclid=IwAR2po4U5a-gdakJVjkU1KKai8xdKgj8HMOAyff5lxmMsXpM8X8439L_Z29A
Культурный десант произвел впечатление на жителей города-побратима Борисово.
